
language: julia

os:
  - linux

julia:
  - 1.3
  - nightly

codecov: true

after_success:
  - julia -e 'using Pkg; cd(Pkg.dir("ChristensenSet")); Pkg.add("Coverage"); using Coverage; Codecov.submit(Codecov.process_folder())'
